spring:
  application:
    name: boundless-books
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect