application:
  flags:
    enable-api-key-validation: ${API_KEY_VALIDATION_ENABLED:true}
  api-key: ${API_KEY:123}
  oauth2:
    redirect-uri: http://localhost:5173
    login-path: /oauth2/authorization/google
    logout-path: /logout

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: true

spring:
  application:
    name: boundless-books
  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:postgresql}
    active: ${DATABASE_PLATFORM:h2}
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  session:
    timeout: 1800
    jdbc:
      initialize-schema: embedded
      table-name: SPRING_SESSION
      cleanup-cron: "0 0 * * * *" # top of every hour of every day
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH2_CLIENT_ID}
            clientSecret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

server:
  servlet:
    session:
      cookie:
        name: BOUNDLESS_BOOKS_SESSION

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
