CREATE TABLE books_metadata
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    author      VARCHAR(255),
    publisher   VARCHAR(255),
    description TEXT,
    CONSTRAINT pk_books_metadata PRIMARY KEY (id)
);