CREATE TABLE books_metadata
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255),
    author          VARCHAR(255),
    publisher       VARCHAR(255),
    category        VARCHAR(255),
    synopsis        TEXT,
    release_date    date,
    cover_image_url TEXT,
    epub_url        TEXT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_books_metadata PRIMARY KEY (id)
);

CREATE TABLE google_users
(
    id         VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    name       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_google_users PRIMARY KEY (id)
);

CREATE TABLE user_favorite_books
(
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE user_profiles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    google_user_id VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

CREATE TABLE user_shelf_books
(
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_GOOGLEUSER FOREIGN KEY (google_user_id) REFERENCES google_users (id);

ALTER TABLE user_favorite_books
    ADD CONSTRAINT fk_usefavboo_on_book_metadata FOREIGN KEY (book_id) REFERENCES books_metadata (id);

ALTER TABLE user_favorite_books
    ADD CONSTRAINT fk_usefavboo_on_user_profile FOREIGN KEY (user_id) REFERENCES user_profiles (id);

ALTER TABLE user_shelf_books
    ADD CONSTRAINT fk_usesheboo_on_book_metadata FOREIGN KEY (book_id) REFERENCES books_metadata (id);

ALTER TABLE user_shelf_books
    ADD CONSTRAINT fk_usesheboo_on_user_profile FOREIGN KEY (user_id) REFERENCES user_profiles (id);